### ISSUE TITLE
ModuleNotFoundError: No module named 'sphinx_markdown_parser'

### ISSUE THREAD

**Issue by shivshankar3578** [codejamninja/sphinx-markdown-builder#31]
as per readme.md  i installed sphinx_markdown_parser and sphinx-markdown-builder both, but still facing error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/local/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 86, in execfile_
    exec(code, _globals)
  File "/Users/roambee1/workspace/jsdoc-example/conf.py", line 18, in <module>
    from sphinx_markdown_parser.parser import MarkdownParser
ModuleNotFoundError: No module named 'sphinx_markdown_parser'
```
Although I'm still able to navigate to MarkdownParser function from
```
from sphinx_markdown_parser.parser import MarkdownParser
```
#### update 
Tried with code example but still facing same issue

I'm a newbie in python, help me, please

**Comment by clayrisser** [comment]
@shivshankar3578 could you send me a link to your project setup?

**Comment by clayrisser** [comment]
This should be fixed now
